### ISSUE TITLE
NullPointerException on typedef declaration in grouping

### ISSUE THREAD

**Issue by mdolk** [yang-central/yangkit#21]
Hi!

Given the following yang-file `null-pointer-example.yang`:
```
module null-pointer-example {
  yang-version 1.1;
  namespace "urn:example:yangkit-bug";
  prefix bug;

  description
    "Demonstrate NullPointerException in io.github.yang-central.yangkit:yangkit-parser:1.3.5";

  revision 2023-07-25 {
  }

  typedef package-version {
    type string {
      pattern '\d+\.\d+([-.](\d+|\w+))*';
    }
  }

  grouping package-meta-data {
    typedef version {
      type package-version;
    }
  }
}
```
And running code like this:
```java
YangSchemaContext schemaContext = YangYinParser.parse(List.of(new File("null-pointer-example.yang")));
schemaContext.validate();
```

I get the following exception:
```
java.lang.NullPointerException: Cannot invoke "org.yangcentral.yangkit.base.YangContext.getTypedef(String)" because "this.yangContext" is null
	at org.yangcentral.yangkit.model.impl.stmt.TypedefContainerImpl.getTypedef(TypedefContainerImpl.java:48)
	at org.yangcentral.yangkit.model.impl.stmt.TypedefContainerImpl.addTypedef(TypedefContainerImpl.java:35)
	at org.yangcentral.yangkit.model.impl.stmt.GroupingImpl.initSelf(GroupingImpl.java:164)
	at org.yangcentral.yangkit.model.impl.stmt.YangStatementImpl.init(YangStatementImpl.java:806)
	at org.yangcentral.yangkit.model.impl.stmt.YangStatementImpl.initChildren(YangStatementImpl.java:741)
	at org.yangcentral.yangkit.model.impl.stmt.YangStatementImpl.init(YangStatementImpl.java:812)
	at org.yangcentral.yangkit.model.impl.schema.YangSchemaContextImpl.validate(YangSchemaContextImpl.java:286)
```
I've reduced the example to be somewhat minimal to trigger the bug.

Hope there can be an easy fix for this :-)

Cheers!
/Mårten

**Comment by lllyfeng** [comment]
@mdolk 
  This issue has been solved, thank you.
